### ISSUE TITLE
Needs to be updated to current standards

### ISSUE THREAD

**Issue by RetroSpector486** [pasqualerossi/So_Long#1]
This project does not have any check for valid path (a.k.a. "Floodfill"), since this is repo is quite popular among students at 42 Adelaide, if you have the time and of course patience, mind if you implement it?

**Comment by pasqualerossi** [comment]
Create a pull request and I'll update the code, thanks!

**Comment by RetroSpector486** [comment]
Sure thing, it's been a while, check your dms :)

**Comment by pasqualerossi** [comment]
Thanks!
